# Generated by Django 5.0.4 on 2024-11-14 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(default='신공학관', max_length=100)),
                ('room_number', models.IntegerField()),
                ('capacity', models.IntegerField(default=1)),
                ('is_checked', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField()),
                ('has_lighting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Professor', 'Professor'), ('Student', 'Student')], max_length=10)),
                ('is_returned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('day_of_week', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resist.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_1', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_2', models.CharField(blank=True, max_length=50, null=True)),
                ('custum_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('reservation_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attendees_count', models.IntegerField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resist.classroom')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resist.user')),
            ],
        ),
    ]
