# Generated by Django 5.0.4 on 2024-11-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resist', '0002_course_custum_tag_course_tag_1_course_tag_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
