# Generated by Django 5.0.4 on 2024-11-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resist', '0003_course_course_name_course_professor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
