# Generated by Django 5.0.4 on 2024-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resist', '0004_alter_course_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='timecheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_1', models.BooleanField(default=True)),
                ('_1h', models.BooleanField(default=True)),
                ('_2', models.BooleanField(default=True)),
                ('_2h', models.BooleanField(default=True)),
                ('_3', models.BooleanField(default=True)),
                ('_3h', models.BooleanField(default=True)),
                ('_4', models.BooleanField(default=True)),
                ('_4h', models.BooleanField(default=True)),
                ('_5', models.BooleanField(default=True)),
                ('_5h', models.BooleanField(default=True)),
                ('_6', models.BooleanField(default=True)),
                ('_6h', models.BooleanField(default=True)),
                ('_7', models.BooleanField(default=True)),
                ('_7h', models.BooleanField(default=True)),
                ('_8', models.BooleanField(default=True)),
                ('_8h', models.BooleanField(default=True)),
                ('_9', models.BooleanField(default=True)),
                ('_9h', models.BooleanField(default=True)),
                ('_10', models.BooleanField(default=True)),
                ('_10h', models.BooleanField(default=True)),
                ('_11', models.BooleanField(default=True)),
                ('_11h', models.BooleanField(default=True)),
                ('_12', models.BooleanField(default=True)),
                ('_12h', models.BooleanField(default=True)),
                ('_13', models.BooleanField(default=True)),
                ('_13h', models.BooleanField(default=True)),
                ('_14', models.BooleanField(default=True)),
                ('_14h', models.BooleanField(default=True)),
            ],
        ),
    ]
